import "@/styles/globals.css";

import { outfit } from "@/fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${outfit.className}`}
      >
        {children}
      </body>
    </html>
  );
}
